title: Baristawerk
description: kaffee
author: marius
remote_theme: "mmistakes/minimal-mistakes"
plugins:
- jekyll-include-cache
header:
  overlay: true  # Optional: Bild mit Overlay
  image: /assets/images/header-image.jpg
  image_position: center  # Bildzentrierung
