excerpt: "This post should display a **header with an overlay image**, if the theme supports it."
header:
  overlay_image: "https://raw.githubusercontent.com/Baristawerk/baristawerk.github.io/refs/heads/main/assets/images/header-image.jpg"
  caption: "Photo credit: [**Unsplash**](https://unsplash.com)"
  actions:
    - label: "More Info"
      url: "https://unsplash.com"

title: Baristawerk
description: kaffee
author: marius
remote_theme: "mmistakes/minimal-mistakes"
plugins:
- jekyll-include-cache

